"""remove scan_depth from world_info_entries

Revision ID: 3b957d10171b
Revises: 533542cfd47e
Create Date: 2025-12-26 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from letta.settings import settings

# revision identifiers, used by Alembic.
revision: str = "3b957d10171b"
down_revision: Union[str, None] = "533542cfd47e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Skip this migration for SQLite
    if not settings.letta_pg_uri_no_default:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("world_info_entries", "scan_depth")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Skip this migration for SQLite
    if not settings.letta_pg_uri_no_default:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("world_info_entries", sa.Column("scan_depth", sa.Integer(), nullable=True))
    # ### end Alembic commands ###

