"""Remove injected_message_id from world_info_injection_states

Revision ID: 43fee82a8eeb
Revises: f3e4d5c6b7a8
Create Date: 2025-12-27 02:29:54.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from letta.settings import settings

# revision identifiers, used by Alembic.
revision: str = "43fee82a8eeb"
down_revision: Union[str, None] = "f3e4d5c6b7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Skip this migration for SQLite
    if not settings.letta_pg_uri_no_default:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("world_info_injection_states", "injected_message_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Skip this migration for SQLite
    if not settings.letta_pg_uri_no_default:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("world_info_injection_states", sa.Column("injected_message_id", sa.String(), nullable=True))
    # ### end Alembic commands ###

