"""add label to world_info_entries

Revision ID: 63cdb17629d0
Revises: cc2ab14f036e
Create Date: 2025-12-27 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63cdb17629d0"
down_revision: Union[str, None] = "cc2ab14f036e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add label column to world_info_entries (nullable/optional)
    op.add_column("world_info_entries", sa.Column("label", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("world_info_entries", "label")
    # ### end Alembic commands ###

