"""add world_info_entries table

Revision ID: ca6df7324851
Revises: 39577145c45d
Create Date: 2025-12-23 22:30:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca6df7324851"
down_revision: Union[str, None] = "39577145c45d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "world_info_entries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("keywords", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("insertion_order", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.Column("case_sensitive", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("match_whole_words", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.Column("scan_depth", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("_created_by_id", sa.String(), nullable=True),
        sa.Column("_last_updated_by_id", sa.String(), nullable=True),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Create index on organization_id and agent_id for faster queries
    op.create_index(
        "ix_world_info_entries_organization_id_agent_id",
        "world_info_entries",
        ["organization_id", "agent_id"],
    )
    op.create_index(
        "ix_world_info_entries_insertion_order",
        "world_info_entries",
        ["insertion_order"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_world_info_entries_insertion_order", table_name="world_info_entries")
    op.drop_index("ix_world_info_entries_organization_id_agent_id", table_name="world_info_entries")
    op.drop_table("world_info_entries")
    # ### end Alembic commands ###

