"""Remove last_processed_run_id from world_info_injection_states

Revision ID: cc2ab14f036e
Revises: 43fee82a8eeb
Create Date: 2025-12-27 02:35:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from letta.settings import settings

# revision identifiers, used by Alembic.
revision: str = "cc2ab14f036e"
down_revision: Union[str, None] = "43fee82a8eeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Skip this migration for SQLite
    if not settings.letta_pg_uri_no_default:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("world_info_injection_states", "last_processed_run_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Skip this migration for SQLite
    if not settings.letta_pg_uri_no_default:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("world_info_injection_states", sa.Column("last_processed_run_id", sa.String(), nullable=True))
    # ### end Alembic commands ###

