"""add cooldown and expiration to world_info_entries, create world_info_injection_states table

Revision ID: f3e4d5c6b7a8
Revises: 3b957d10171b
Create Date: 2025-12-26 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3e4d5c6b7a8"
down_revision: Union[str, None] = "3b957d10171b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add cooldown and expiration columns to world_info_entries
    op.add_column("world_info_entries", sa.Column("cooldown", sa.Integer(), nullable=True))
    op.add_column("world_info_entries", sa.Column("expiration", sa.Integer(), nullable=True))
    
    # Create world_info_injection_states table
    op.create_table(
        "world_info_injection_states",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_info_entry_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("injected_message_id", sa.String(), nullable=True),
        sa.Column("last_processed_run_id", sa.String(), nullable=True),
        sa.Column("current_cooldown", sa.Integer(), nullable=True),
        sa.Column("current_expiration", sa.Integer(), nullable=True),
        sa.Column("cooldown_setting", sa.Integer(), nullable=False),
        sa.Column("expiration_setting", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("_created_by_id", sa.String(), nullable=True),
        sa.Column("_last_updated_by_id", sa.String(), nullable=True),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["world_info_entry_id"],
            ["world_info_entries.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("world_info_entry_id", "agent_id", name="uq_world_info_entry_agent"),
    )
    
    # Create indexes
    op.create_index(
        "ix_world_info_injection_states_entry_agent",
        "world_info_injection_states",
        ["world_info_entry_id", "agent_id"],
    )
    op.create_index(
        "ix_world_info_injection_states_organization_id",
        "world_info_injection_states",
        ["organization_id"],
    )
    op.create_index(
        "ix_world_info_injection_states_agent_id",
        "world_info_injection_states",
        ["agent_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index("ix_world_info_injection_states_agent_id", table_name="world_info_injection_states")
    op.drop_index("ix_world_info_injection_states_organization_id", table_name="world_info_injection_states")
    op.drop_index("ix_world_info_injection_states_entry_agent", table_name="world_info_injection_states")
    
    # Drop table
    op.drop_table("world_info_injection_states")
    
    # Remove columns from world_info_entries
    op.drop_column("world_info_entries", "expiration")
    op.drop_column("world_info_entries", "cooldown")
    # ### end Alembic commands ###

